title: 2025 WiCyS Target CTF
description: CTF write-ups for the 2025 Target Defense Challenge
baseurl: "/2025_wicys_target_ctf"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-optional-front-matter
