title: 2025 WiCyS Target Cyber Defense CTF
description: CTF write-ups for the 2025 Target Cyber Defense Challenge
hero:
  heading: "2025 Target + WiCyS Cyber Defense Challenge CTF Write-Ups"
  text: "This page showcases my participation in the 2025 Target Cyber Defense CTF Challenge hosted by WiCyS, which ran from July 1 through August 14, 2025."
baseurl: "/2025_wicys_target_ctf"
url: "https://glsanclem.github.io"
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
